### ISSUE TITLE
Do a comparison, starting with YAML files.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#113]
A published comp including comparison to FS from flare-timing is a static site. The user interface is a single page app that gets its data as `*.json` files from the same site. To generate those `*.json` files, I run a server that reads data from `*.yaml` files on local disk. There's only a few of those files that relate to FS. We could substitute airscore data for FS data in those `*.yaml` files. I run a script that runs `curl` requests to localhost:port while the server is serving a single comp and save each request with an `accept: application/json` header to a `*.json` file to be deployed to the static site.

We could have airscore export an `*.fsdb` file from which I extract that set of `*.yaml` files for doing the comparison with but that seems to be an unnecessary step.

JSON is convertible to YAML so a REST API could be added to airscore to supply the limited data I need for the comparison, responding to `accept: application/json` or `accept: text/yaml` or both. If you supply only JSON I can convert it offline to YAML and my server will be good to go.

The endpoints of my server that serve JSON are:

```
/fs-effort/#task/landing
/fs-route/#task/sphere
/fs-route/#task/ellipse
/fs-score/validity
/fs-score/#task/validity-working
/fs-score/#task/score
/fs-mask-track/#task/arrival
/stats/point-diff -- the points differences between FS and flare-timing
```

To serve a JSON file my server might read one or more YAML files.

You can see this data in action using the browser devtools and looking at the XHR network traffic for any of the comps I've published such as http://2012-forbes.flaretiming.com. The YAML files for this comp can be found at https://github.com/FlareTiming/2012-forbes-flatlands-score. The files with the FS related data are those with `norm` in their names:

```
*.norm-arrival.yaml
*.norm-effort.yaml
*.norm-land-out.yaml
*.norm-route.yaml
*.norm-score.yaml
```

This issue is a feature request of airscore to supply the data I require for a comparison, the data in the YAML files. I'd expect you'd be prefixing paths supplying the data I need with something in airscore to identify the comp.

**Comment by philderbeast** [comment]
In response to your question "Is fraction the portion of max points available?" @kuaka the `frac` fields are the fraction allocated to this pilot from points available for one of distance (reach and effort), time, leading or arrival.

```yaml
# *.norm-arrival.yaml
pilotsAtEss:
- 0
- 32
- 46
- 37
- 27
- 46
- 7
- 29
arrivalRank:
- [] # no pilot made goal in the 1st task
- - - - '103'
      - Roberto Nichele
    - lag: 0.000000 h
      rank: '1'
      frac: 1 # Roberto got all of the available arrival points
  - - - '89'
      - Scott Barrett
    - lag: 0.003611 h
      rank: '2'
      frac: 0.93333713 # Scott got this fraction of the available arrival points.
```

**Comment by philderbeast** [comment]
```yaml
# *.norm-effort.yaml
...
  - chunk: 163
    startChunk: 16.3 km
    endChunk: 16.4 km
    endAhead: 20.3 km # the end of the lookahead when looking for "downward" pilots.
    down: 1 # number of pilots down in this chuck
    downs: # the exact distance where the pilots came down
    - 16.363 km
    downers: # pilots who came down (landed) in this chunk, there's only one.
    - - '5' # Wolfgang's pilot number
      - Wolfgang Siess
    downward: 3 # there are 3 pilots who will land within the lookahead distance
    rel: 5.3191e-4
    frac: 0.15305851 # Wolfgang got this fraction of distance points (maximum for effort is 0.5 of distance)
  - chunk: 164
    startChunk: 16.4 km
    endChunk: 16.5 km
    endAhead: 20.4 km
    down: 1
    downs:
    - 16.409 km # 1st of 3 downers from chunk 163, Boris
    downers:
    - - '27'
      - ! 'Boris Marold '
    downward: 2
    rel: 3.9894e-4
    frac: 0.15345745
  - chunk: 181
    startChunk: 18.1 km
    endChunk: 18.2 km
    endAhead: 22.1 km
    down: 1
    downs:
    - 18.196 km # 2nd of 3 downers from chunk 163, Chris
    downers:
    - - '105'
      - Chris Lawry
    downward: 1
    rel: 2.6596e-4
    frac: 0.15797872
  - chunk: 193
    startChunk: 19.3 km
    endChunk: 19.4 km
    endAhead: 23.3 km
    down: 1
    downs:
    - 19.355 km # 3rd of 3 downers from chunk 163, Kari
    downers:
    - - '55'
      - Kari Suhonen
    downward: 1
    rel: 2.6596e-4
    frac: 0.16117021
```

**Comment by philderbeast** [comment]
```yaml
# *.norm-score.yaml
...
  - - - '5'
      - Wolfgang Siess
    - breakdown:
        distance: 130.4 # Wolfgang got 130.4 points for distance
        leading: 0
        arrival: 0
        time: 0
        # NOTE: The breakdown of distance points into effort points and reach points.
        # 91.15 + 39.22 = 130.37, rounds to 130.4.
        effort: 91.15
        reach: 39.22
      place: '68' # 68th placing in this task
      total: 130 # Total points in this task
      fractions:
        # NOTE: distance is made up in equal parts from reach and effort
        # 0.30664062 + 0.13193393 = 0.43857455 => divide by 2 => 0.219287275
        distance: 0.21934399
        leading: 0
        arrival: 0
        time: 0
        # TODO: Find out why effort in score breakdown is not exactly twice what it is in `*.norm-effort.yaml`.
        # 2 x 0.15305851 = 0.30611702
        effort: 0.30664062 # fraction of effort points
        reach: 0.13193393 # fraction of reach points
      reach:
        extra: 16.363000 km
        flown: 16.363000 km
      landedMade: 16.333000 km
      ss: 2012-01-05T02:53:20Z
      es: null
      timeElapsed: null
      # NOTE: The leading area units are km^2 s in this case but for some comps it's km s.
      leadingArea: 1810441.0000 km^2 s
      leadingCoef: 8.14889592
```

To be consistent, I should change `frac` in `*.norm-effort.yaml` to be twice what it is now so that it is shown as a fraction of effort points rather than as a fraction of distance points.

**Comment by kuaka** [comment]
thanks for the explanations. I'll probably leave effort/difficulty until last as I am less familiar with it and at least we can do PG before it is done.

**Comment by kuaka** [comment]
>       reach:
>        extra: 16.363000 km
>       flown: 16.363000 km

What is reach? I assuem flown is max distance. is extra to do with glide bonuses ?
in the YAML is it necessary to have units (km,h) (seems a bit verbose)?

**Comment by philderbeast** [comment]
Reach is linear distance and effort is distance difficulty.

**Comment by philderbeast** [comment]
```yaml
- gsBestTime: 3.883611 h
  nominalDistance: 80.0 km
  nominalTime: 2.000000 h
  reachMax:
    extra: 217.365000 km
    flown: 217.365000 km
  ssBestTime: null
```

> What is the difference/definition of gsBestTime v ssBestTime?

@kuaka I check speed and pace. For speed the clock starts when the gate taken opens but for pace it starts when the pilot crosses the start and for these fields I use [g, s](https://github.com/BlockScope/flare-timing/blob/2e46175a58781aa0f44812de6a21cc7f352f39df/lang-haskell/comp/library/Flight/Track/Point.hs#L63-L67) and e prefixes for *gate*, *start* and *end*.

The [MaskingSpeed](https://github.com/BlockScope/flare-timing/blob/2e46175a58781aa0f44812de6a21cc7f352f39df/lang-haskell/comp/library/Flight/Track/Mask/Speed.hs#L28-L31) record has `gsBestTime` and `ssBestTime` fields.

**Comment by philderbeast** [comment]
> is it necessary to have units (km,h) (seems a bit verbose)?

A main goal of flare-timing was to be able to scrutinise files and not start up a debugger to see how some scores were worked out. The units are there so that humans don't have to guess at units.

**Comment by philderbeast** [comment]
The section of the GAP rules about the [scored time window](https://github.com/BlockScope/CIVL-GAP/blob/51af045ad52db1220172f4331a6b9267adf17296/sec-special-cases.tex#L164).

**Comment by kuaka** [comment]
regarding the yaml files etc. you mentioned that you could make them from fsdb, which makes me think that all the parameters are or should be present in the fsdb files. Is this the case? I can't see some of them in the fsdb files that airscore creates.

another question: what do you do when the info is not relevant in the yaml file (e.g. effort in a PG comp.) is it null? or is that line excluded?

regarding reach and effort for distance,  my understanding is that this is a choice if to use difficulty or distance for distance points when setting up a competition (airscore is like that) so we are using one and storing it, not both. Does flare timing require both? presumably it only needs the one that is used to calculate the score..?

**Comment by kuaka** [comment]
in Australia Forbes 2012.norm-score.yaml  see that each task has a validityWorkingStop. What is the logic here when tasks are not stopped?

**Comment by philderbeast** [comment]
@kuaka FS always writes the validity attribute and it is `stop_validity="1"` when the task is not stopped. The attributes I need to work out the working are also always written. When I score with flare-timing, I don't bother with the working for stop validity if the task was not stopped. You can do the same.

```
# *.gap-point.yaml
validityWorking:
- time: ...
  launch: ...
  distance: ...
  stop: null
```
