### ISSUE TITLE
FsTask@tracklog_folder to match the IGC file

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#117]
When exporting an `*.fsdb` please set `FsTask@tracklog_folder` to match the IGC file download filename for that task.

```xml
<!-- *.fsdb -->
    <FsTasks>
      <FsTask id="1" name="Task 1" tracklog_folder="">
```

```yaml
# *.comp-input.yaml
taskFolders:
- - ''
- - ''
- - ''
- - ''
- - ''
- - ''
pilots:
- - - - '115'
      - Alberto Castagna
    - alberto_castagna_2020-08-02_01.igc
  - - - '141'
      - Albino Malli
    - albino_malli_2020-08-02_01.igc
```

```
> ls *.zip
t1_20200802.zip  t2_20200804.zip  t3_20200805.zip  t4_20200806.zip  t5_20200807.zip  t6_20200808.zip
```

When `FsTask@tracklog_folder` matches the IGC zip file name, extracting zip archives to files of the same name is the convenient and scoring can proceed in `flare-timing` without any hand editing intervention. The `*.comp-input.yaml` will use those same folders for tracklogs.

```diff
-- taskFolders:
-- - - ''
-- - - ''
-- - - ''
-- - - ''
-- - - ''
-- - - ''
taskFolders:
++ - - t1_20200802
++ - - t2_20200804
++ - - t3_20200805
++ - - t4_20200806
++ - - t5_20200807
++ - - t6_20200808
```
