### ISSUE TITLE
Set values in attributes FsFlightData/@iv and FsResult/@last_distance

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#121]
@kuaka I was unable to parse out the scores from the `*.fsdb` you provided to me for the Italian Open 2020
2020-08-01 to 2020-08-08, Santa Elisabetta comp:

```yaml
# *.norm-score.yaml
score:
- []
```

I cut down that file to one pilot and one task and compared it to another also cut down in the same way. I found that the airscore export is not setting values for two attributes. Here's the change I made to get it to work with other attributes omitted:

```diff
-- <FsFlightData iv=""/>
-- <FsResult last_distance=""/>
++ <FsFlightData iv="0"/>
++ <FsResult last_distance="0"/>
```

Now running `fs-score` generates a score:

```yaml
score:
- - - - '111'
      - Marco Busetta
    - breakdown:
        distance: 407.4
        leading: 140.6
        arrival: 0
        time: 438
        effort: 0
        reach: 407.4
      place: '4'
      total: 986
      fractions:
        distance: 1
        leading: 1
        arrival: 0
        time: 1
        effort: 0
        reach: 1
      reach:
        extra: 52.075000 km
        flown: 52.075000 km
      landedMade: 0.000000 km
      ss: 2020-08-02T10:45:00Z
      es: 2020-08-02T12:54:01Z
      timeElapsed: 2.150278 h
      leadingArea: 0.0000 km^2 s
      leadingCoef: 1.4547724
```

Could we please set values in attributes `FsFlightData/@iv` and `FsResult/@last_distance` when exporting?
